### ISSUE TITLE
DMCA takedown process

### ISSUE THREAD

**Issue by andreimarcu** [andreimarcu/linx-server#166]
- Add ```-dmca-email dmca@linx.server``` flag which will add a page in the navigation with instructions to email for DMCA takedowns.
- Add ```-sha256blacklist myblacklist.txt``` flag which contains sha256sums (one per line) that are not allowed to be uploaded (check against this list when uploading)
- Create a script for the admin that will replace the file with a notice that the file at that url as been removed as part of a dmca takedown, and appends the sha256 of the offending file to the sha256blacklist
  
  
  
- Could also have a way to provide a custom html page instead of the default one with the email

**Comment by mutantmonkey** [comment]
If we want to have the ability to support counternotices, it might be better to just disable access to content instead of removing it from the storage backend, which we might be able to do with another metadata flag or something. Looking at the S3 API though, I'm not sure if it will be possible to update the metadata after a file is already uploaded...that's something we'll probably want to look into. We'll also need to add a method to the backend interface to support that.

**Comment by GFYSC** [comment]
So glad your taking a look at this, as my site recently hit 10k Views per day mark, and what used to be my main domain before switching was banned by CloudFlare for hosting malicious content that they never made me aware of or warned me to take down.

If it helps it was this site - URLhaus.abuse.ch/host/finndev.net - once they receive a report from someone they auto send emails to both DMCA addresses of CF & Google.

Also my suggestions would be

- A "Report" button that could silently count to a certain number set by admin before Auto adding DMCA notice to the page and deleting / await for approval?

- A DMCA Report page that could log to a file for a Admin instead of an email, with that you could have it if a admin does not attend to the file in 3 days then remove the file / add DMCA to it. (3 Days is what Google gives)

I'm not always around, so an automated solution would be nice that didn't need such a manual intervention.

**Comment by MyUncleSam** [comment]
Is this a comming commanline parameter? Because it cannot be used in the up2date version.
