### ISSUE TITLE
file download with original name(file name's save as UTF-8)

### ISSUE THREAD

**Issue by osias10** [andreimarcu/linx-server#239]
If I don't check randomize file name and I upload English file name then I can download with original file name 
But if I upload file which name is Korean then file name is change, So I can't know original file name

I think this program support only English file name So can you save file name with UTF-8 when I don't check randomize file name button?

**Comment by andreimarcu** [comment]
The filename is currently restricted to: `[^A-Za-z0-9\-]` (https://github.com/andreimarcu/linx-server/blob/master/upload.go#L365)

There's an older issue for keeping original file names so that you can download them as uploaded https://github.com/andreimarcu/linx-server/issues/77

Feel free to send a PR if you want to implement this
