### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by andreimarcu** [andreimarcu/linx-server#27]
Optionally enable API key(s) requirement. 

This would involve a Config.ApiKeys as an array of keys, a UpReq.ApiKey field for upload requests that the processUpload will then check against.
Also a template change on the index and paste to check if api keys are enabled, don't show the uploader and paster

**Comment by mutantmonkey** [comment]
I looked into this, and I think the best way to implement this is to write middleware to check HTTP authentication for POST, PUT, and DELETE requests. This being said, is there any reason this needs to be done in linx-server itself? It can easily be handled by nginx.

I think it might be better to leave this as a future enhancement, rather than implement it now.
