### ISSUE TITLE
Filename / Extensions: renaming example.tar.gz to exampletar.gz

### ISSUE THREAD

**Issue by aerth** [andreimarcu/linx-server#74]
Currently, uploading example.tar.gz renames to exampletar.gz

There are some files *out there* that are named like: ```example.one.jpg``` or ```example.one.jpg.zip``` using dots in ways that are not just .ext

Not sure if this is something intentional.

I feel example.tar.gz should stay example.tar.gz

Edit: *I am working around this by just using .tgz files by the way*

**Comment by andreimarcu** [comment]
It's intentional for now, but not necessarily ideal.

This can go two ways: 

1. Have a list of common two-part extensions
2. Allow arbitrary number of dots in the filename (which can, and does screw up filename randomization)


I'm personally inclined to go with 1) but won't have time to work on it right now

**Comment by aerth** [comment]
Even if you don't have time to work on it, it is good to hear which direction you'd like to go.

**Comment by mutantmonkey** [comment]
My vote is for 1 and I might have the time to work on this soon.
